# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - fr5_arm_controller

  fr5_arm_controller:
    type: FollowJointTrajectory
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6