enable_point_cloud: true
enable_colored_point_cloud: false
point_cloud_decimation_filter_factor: 4

enable_color: true
color_width: 640
color_height: 480
color_fps: 15
color_format: "ANY"

enable_depth: true
depth_width: 640
depth_height: 480
depth_fps: 15
depth_format: "ANY"

depth_registration: false
align_mode: "SW"

color.image_raw.enable_pub_plugins:
  - image_transport/raw

depth.image_raw.enable_pub_plugins:
  - image_transport/raw

depth_qos: "sensor_data"
depth_camera_info_qos: "sensor_data"

# cloud_frame_id: camera_link